### PR TITLE
fix: reset CARGO env var to fix wrong CARGO in commands

### LINKED ISSUE #1059: `CARGO` env variable does not get set when running commands
### Describe The Bug
The README describes 

> When defined with scripts (as opposed to commands), the CARGO environment variable will be defined for the requested toolchain.

Although this says it doesn't define it for commands, I think this should so that the behavior matches with running via `rustup` or `cargo +toolchain`.

### To Reproduce
`build.rs`:
```
use std::path::PathBuf;
use std::env;

fn main() {
    panic!("{:#?}", env::var("CARGO").map(PathBuf::from).unwrap());
}
```

`Makefile.toml`:
```
[tasks.nightly-build]
toolchain = "nightly"
extend = "build"
```

These commands panic with stable toolchain path:
`cargo build`
`rustup run stable cargo build`
`cargo make build`
`cargo make nightly-build`

These commands panic with nightly toolchain path:
`cargo +nightly build`
`rustup run nightly cargo build`

The issue here is that `cargo make nightly-build` should print the nightly toolchain path. Something in cargo-make is preventing it from doing that.

### PR DESCRIPTION
**Pull request by wmmc88**
fixes #1059

### CODE REVIEW

File: src/lib/toolchain_test.rs [hunk 1]
```diff
@@ -124,16 +124,19 @@ fn get_cargo_binary_path_valid() {
 #[test]
 #[ignore]
```
Comment (wmmc88) [inline src/lib/toolchain_test.rs:125]: This test is ignored in CI. Any reason for this @sagiegurari

**Comment by wmmc88** [comment]
`codecov/project` seems to be failing because it considers the `toolchain_test.rs` file as requiring tests

File: src/lib/toolchain.rs [hunk 2]
```diff
@@ -148,5 +148,5 @@ pub(crate) fn get_cargo_binary_path(toolchain: &ToolchainSpecifier) -> Option<St
 }
 
 pub(crate) fn remove_rust_env_vars() {
-    envmnt::remove_all(&vec!["RUSTC", "RUSTDOC", "RUSTFLAGS"]);
+    envmnt::remove_all(&vec!["CARGO", "RUSTC", "RUSTDOC", "RUSTFLAGS"]);
```
Comment (sagiegurari) [inline src/lib/toolchain.rs:151]: ok i remember this. this was to fix the cargo bug. good that you found it.

File: src/lib/toolchain_test.rs (hunk 1 above)
Comment (wmmc88) [reply src/lib/toolchain_test.rs:125]: hmm. I'm not entierly sure how `ci-flow` executes this particular test, but my guess is that since `env::set_var` isn't safe for multi-threaded environments and some other test executing in parallel will change the env var and that spuriously causes this test to fail.

**Comment by sagiegurari** [comment]
sorry fir the delay. I'll meege and publish a new version mid next week

**Comment by wmmc88** [comment]
> sorry fir the delay. I'll meege and publish a new version mid next week

friendly bump 🙂

**Comment by sagiegurari** [comment]
@wmmc88 thanks a lot. looks good. i'm merging to dev branch, doing few checks, check other issues and than i'll release.
